# Generated by Django 3.2.3 on 2021-05-15 19:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('proberty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('a', django.db.models.manager.Manager()),
            ],
        ),
    ]
