# Generated by Django 3.2.2 on 2021-05-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proberty', '0003_auto_20210516_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
