# Generated by Django 3.2.2 on 2021-05-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proberty', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_category', to='proberty.category'),
            preserve_default=False,
        ),
    ]
